### PR TITLE
[Vue warn]: Invalid handler for event "click": got undefined

### PR DESCRIPTION
**Pull request by Pistacchione**
Modify onEsc an onClickMask from watch to methods.

### CODE REVIEW

**Comment by Pub4Game** [comment]
@chenjiahan migrate

**Comment by chenjiahan** [comment]
@Pistacchione Sorry to be replying so late, this is a terrible mistake and thanks for your PR. I have released vodal@2.3.1, please try it.

**Comment by Pistacchione** [comment]
@chenjiahan perfect thank you! 👍

**Comment by Pub4Game** [comment]
@chenjiahan Thanks! 😜

**Comment by fubarpatsharp** [comment]
@chenjiahan thank you.

**Comment by chenjiahan** [comment]
My pleasure 😃

**Pull request merged**
